# Generated by Django 4.1.4 on 2022-12-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='businessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('businessName', models.CharField(max_length=70)),
                ('businessLocation', models.CharField(max_length=100)),
                ('businessCategory', models.CharField(max_length=70)),
                ('businessDescription', models.CharField(blank=True, default='N/A', max_length=200)),
                ('image', models.ImageField(upload_to='business/images')),
            ],
        ),
    ]
